language: java
jdk:
- oraclejdk8
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAI3XGM2S2K2A6SKZQ
  - AWS_DEFAULT_REGION=eu-west-1
  - secure: QUAs90MSfHfGVohTY0Lj9oWQN9RoohHwEJIvqzzM0f6YX05CJGuYKv9yUJB/VILlvRb5Qk9wWthyp+gtYb35b7zQezSzpfj55qbQHmz5fJDeuF0xMvrX8GLV5Uix2HVkXmTmrfU2iGe4jujUaHzgUVh63JJan96e1eTqYnGj4x1RS9D2wTsJZzYzFNyk1sxltZK/51s0mr48/Rso/MG6JYktPHhU3B0GmXdq8pwQuO//1+obbJMkZcKNb4+LeqysPDVT+P150L5mc+MLu+MOcAhEQAG0KIwuXxfKiR6oF/0D6ViGMTIOiBcihQvFwR4wLJXV9HnthwOfXq8S5NocN5kXuifaX3GoSsx8I4KF9tpXxUMuYCwazCpEuWVpvoL7zNx1jShggUbOPoCY5bLrr+L3JGqFVB9LYLWyoC+rF/+DH+enhXLStct82usADvENCXDURXtMmT5AaPvUsrTC2c3YUd09g5gVOp2JwDDfZCr6bHzYxG+y+UqcVv2yPjNIczZcdhNYf1qZBLqsxwWTL41gjgKnNDks2re9AQY+13oZgFiscGEILsW3w8oBkfEjJoA12gxTLepmuGiziO4zgjnZGsYmtISKlDLafWQW6FFJYHKTvE47dVgM0xmpn1L6A5LgSGztQJ3q6AW+HkkqvOcd+yKBSekK0eV7wOh7pPU=
before_install:
- pip install --upgrade --user awscli
deploy:
- provider: releases
  api_key:
    secure: Y2TBAKh0mrzfQKiOrSeuEtaAUZWCwz+XOZD7xLiBa7VgTFJscNTzTj/DR1yzGBzqX567qubUfBCN9/jRHB7GoYf2FNQVW92Fpk5higz+X0PAxYUsNkfTt8GhoLPHvk640wx5nToeriLRrfgB8pXDM8fvvHlgV1sGSRMQOxwzw1qWrXBhv9euUE68ZoN1sK+xyE22ewGSz2l7pMVh2DGu92s161ilIr3RTcR8l22tx5CkJY7/fja4BumGfzhDLMr+Oiq8obJO6UAP7kZhzPfc9mc/HWwqslCuLRWASQNcUOVqpKux4e5onWpKWajaFWVsuUbAgWhzto9lG86FM/WgjDw/hLNrDBxpdXPslN9R4JfYiUf7716cPtwO9gZLmOGV1MLaC1cM+0mAICoXjTSAa1SFaF3Chtpwv0uiQiOZYlhqpaxYqxOCiAwURL1U4E+SG9WZaiN1LU0ZZpXdEUT/0halA+CzX4bdr3W/ZrnJU+o6muYvCfSxtFHB4J3lQgJ3ahKi1SKbshJTIS8nl6CiZX3z+6ovfiy9C4pUk1MxMNuX37oBliWMhqUG4LGyo0kvO1a5b/TfOXAi2U4jpIEqRJBVZMG3QIE17MupJpoH0PwZ8ILr5C5aRtpAtGcTF6xDdbw8v8WJEmTF/gU4vnTOTIJ1z8hWgiiZR76XrttaSCI=
  file: alexa-menu-skill/target/alexa-menu-skill-*.jar
  file_glob: true
  skip_cleanup: true
  on:
    repo: witspirit/alexa-menu
    tags: true
- provider: script
  skip_cleanup: true
  script: devops/scripts/update_lambda.sh ${TRAVIS_TAG}
  on:
    repo: witspirit/alexa-menu
    tags: true

